# Page settings
baseurl = "localhost:1313"
title = "Francesco Oteri"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  author = "Francesco OTERI"
  description = "Personal website of Francesco Oteri, sharing research papers and projects"
  custom_css = ["css/papers-custom.css", "css/papers-carousel.css"]
  
  # Navigation
  [params.navigation]
    brand = "Francesco OTERI"
    home = "Home"
    papers = "Papers"
    about = "About"
    contact = "Contact"

  # Hero section
  [params.hero]
    enable = true
    title = "Research in Computational Biology"
    subtitle = "Exploring molecular dynamics, protein evolution, and genomics"

  # Papers section
  [params.papers]
    enable = true

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "Research in computational biology and bioinformatics"

  # Contact section
  [params.contact]
    enable = true
    title = "Contact"
    description = "Get in touch"

  # Footer section
  [params.footer]
    enable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
